// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxen4b_g7UjfLfnqi6Goof6Wqo368NcDY',
    appId: '1:598818926841:web:412dc7382e7f68ac157228',
    messagingSenderId: '598818926841',
    projectId: 'motova-8cca8',
    authDomain: 'motova-8cca8.firebaseapp.com',
    storageBucket: 'motova-8cca8.firebasestorage.app',
    measurementId: 'G-ZGJ7CFX05P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKG53yTlMqGPV0W6yZuWSK051dQkF5c8',
    appId: '1:598818926841:android:d6dc6b2f58c62d0d157228',
    messagingSenderId: '598818926841',
    projectId: 'motova-8cca8',
    storageBucket: 'motova-8cca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTk8MzljMG5xalzmHWBDz7QYNFerGAOJA',
    appId: '1:598818926841:ios:1a272dcc1dc3b2e0157228',
    messagingSenderId: '598818926841',
    projectId: 'motova-8cca8',
    storageBucket: 'motova-8cca8.firebasestorage.app',
    iosBundleId: 'com.example.motovaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTk8MzljMG5xalzmHWBDz7QYNFerGAOJA',
    appId: '1:598818926841:ios:1a272dcc1dc3b2e0157228',
    messagingSenderId: '598818926841',
    projectId: 'motova-8cca8',
    storageBucket: 'motova-8cca8.firebasestorage.app',
    iosBundleId: 'com.example.motovaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxen4b_g7UjfLfnqi6Goof6Wqo368NcDY',
    appId: '1:598818926841:web:544facab92b58bce157228',
    messagingSenderId: '598818926841',
    projectId: 'motova-8cca8',
    authDomain: 'motova-8cca8.firebaseapp.com',
    storageBucket: 'motova-8cca8.firebasestorage.app',
    measurementId: 'G-B137N6T7ET',
  );
}
